export const albums = [
  { name: "A Verdadeira Historia do Natal", tracks: 22 },
  { name: "Aprendi com meu Pai", tracks: 15 },
  { name: "Brilha a estrela", tracks: 0 },
  { name: "Coletânea de dia das mães", tracks: 16 },
  { name: "Coletânea de Dia dos Pais", tracks: 10 },
  { name: "Coletânea de Natal", tracks: 18 },
  { name: "Coletânea de páscoa", tracks: 18 },
  { name: "Datas Comemorativas 1", tracks: 18 },
  { name: "Datas Comemorativas 2", tracks: 18 },
  { name: "Datas Comemorativas 3", tracks: 17 },
  { name: "Datas Comemorativas 4", tracks: 18 },
  { name: "Datas Comemorativas 5", tracks: 0 },
  { name: "Datas comemorativas 6", tracks: 0 },
  { name: "Datas Comemorativas 7", tracks: 18 },
  { name: "Datas Comemorativas 8", tracks: 19 },
  { name: "De repente mãe", tracks: 5 },
  { name: "EBD", tracks: 20 },
  { name: "Em busca do presente maior", tracks: 12 },
  { name: "Favoritas", tracks: 0 },
  { name: "Favoritas 2", tracks: 20 },
  { name: "Gratidão", tracks: 17 },
  { name: "Homenagem", tracks: 19 },
  { name: "Inexplicável Amor", tracks: 16 },
  { name: "Jesus, a alegria do Natal", tracks: 16 },
  { name: "Já Nasceu", tracks: 30 },
  { name: "Louvores da Garotada 1", tracks: 20 },
  { name: "Louvores da Garotada 2", tracks: 20 },
  { name: "Louvores da Garotada 3", tracks: 0 },
  { name: "Louvores da Garotada 4", tracks: 21 },
  { name: "Louvores da Garotada 5", tracks: 20 },
  { name: "Louvores da Garotada 6", tracks: 20 },
  { name: "Louvores da Garotada 7", tracks: 23 },
  { name: "Louvores da Garotada 8", tracks: 21 },
  { name: "Meu pai, meu amigo", tracks: 18 },
  { name: "Minha Doce Páscoa", tracks: 19 },
  { name: "Mãe inesquecível", tracks: 15 },
  { name: "O nascimento do Rei", tracks: 25 },
  { name: "O que é Páscoa", tracks: 22 },
  { name: "O Sentido da Páscoa", tracks: 22 },
  { name: "O Sentido do Natal 2", tracks: 20 },
  { name: "Simplesmente Mãe", tracks: 20 },
  { name: "Teus passos vou seguir", tracks: 15 },
  { name: "Um presente chamado mãe", tracks: 20 },
  { name: "Um presente para todos", tracks: 24 },
  { name: "Um sonho de Páscoa", tracks: 24 },
  { name: "Uma lição de Páscoa", tracks: 18 },
  { name: "Zero a seis anos", tracks: 18 },
  { name: "É Natal", tracks: 28 }
];
